apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: vault
  region: us-west-2
  version: "1.16"
nodeGroups:
  - name: default
    instanceType: t2.xlarge
    desiredCapacity: 3
    ssh:
      allow: true
    volumeSize: 50
