# This is an example of how to load in a vault config from a Kubernetes Secret
apiVersion: v1
kind: Secret
metadata:
  name: config-from-secret
  labels:
    app.kubernetes.io/name: vault-configurator
    vault_cr: vault
stringData:
  vault-config.yml: |
    policies:
    - name: allow_access_to_secrets_from_secret
      rules: path "secret/*" {
        capabilities = ["create", "read", "update", "delete", "list"]
        }
